//////////////
// Sala1.1//
/////////////
var scheduleWeek_1_sala_11 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["03/07/2017", "04/07/2017", "05/07/2017", "06/07/2017", "07/07/2017", "08/07/2017", "09/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_2_sala_11 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["10/07/2017", "11/07/2017", "12/07/2017", "13/06/2017", "14/07/2017", "15/07/2017", "16/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_3_sala_11 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["17/07/2017", "18/07/2017", "19/07/2017", "20/06/2017", "21/07/2017", "22/07/2017", "23/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_4_sala_11 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["24/07/2017", "25/07/2017", "26/07/2017", "27/07/2017", "28/07/2017", "29/07/2017", "30/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};
//////////////
// Sala1.2//
/////////////
var scheduleWeek_1_sala_12 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["03/07/2017", "04/07/2017", "05/07/2017", "06/07/2017", "07/07/2017", "08/07/2017", "09/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_2_sala_12 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["10/07/2017", "11/07/2017", "12/07/2017", "13/06/2017", "14/07/2017", "15/07/2017", "16/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_3_sala_12 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["17/07/2017", "18/07/2017", "19/07/2017", "20/06/2017", "21/07/2017", "22/07/2017", "23/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_4_sala_12 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["24/07/2017", "25/07/2017", "26/07/2017", "27/07/2017", "28/07/2017", "29/07/2017", "30/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};
//////////////
// Sala 1.3//
/////////////
var scheduleWeek_1_sala_13 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["03/07/2017", "04/07/2017", "05/07/2017", "06/07/2017", "07/07/2017", "08/07/2017", "09/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_2_sala_13 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["10/07/2017", "11/07/2017", "12/07/2017", "13/06/2017", "14/07/2017", "15/07/2017", "16/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_3_sala_13 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["17/07/2017", "18/07/2017", "19/07/2017", "20/06/2017", "21/07/2017", "22/07/2017", "23/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_4_sala_13 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["24/07/2017", "25/07/2017", "26/07/2017", "27/07/2017", "28/07/2017", "29/07/2017", "30/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};
//////////////
// Sala1.4//
/////////////
var scheduleWeek_1_sala_14 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["03/07/2017", "04/07/2017", "05/07/2017", "06/07/2017", "07/07/2017", "08/07/2017", "09/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_2_sala_14 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["10/07/2017", "11/07/2017", "12/07/2017", "13/06/2017", "14/07/2017", "15/07/2017", "16/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_3_sala_14 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["17/07/2017", "18/07/2017", "19/07/2017", "20/06/2017", "21/07/2017", "22/07/2017", "23/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};

var scheduleWeek_4_sala_14 = {
    "hour": ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"],
    "dates": ["24/07/2017", "25/07/2017", "26/07/2017", "27/07/2017", "28/07/2017", "29/07/2017", "30/07/2017"],
    "0": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "1": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "2": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "3": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "4": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "5": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"],
    "6": ["Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível", "Disponível"]
};
